version: "3.3"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=kaddem
    networks:
      - springapimysql-net
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
  app:
    container_name: app
    depends_on:
      - mysqldb
    image: asmahejaiej/jenkins-releases:v1.0.0
    networks:
      - springapimysql-net
    environment:
      - database=mysqldb
      - password=root
    ports:
      - 8089:8089
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db:

networks:
  springapimysql-net:
    driver: bridge