version: "3.3"
services:
  mysqldb:
    container_name: mysqldb
    image: mysql:8
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD =
      - MYSQL_DATABASE = kaddem
    volumes:
      -  /home/mysql/data:/var/lib/mysql
    ports:
      - 3036:3036


  spring_app:
    image: hanine04/devopsimage
    container_name: wonderful_pasteur
    restart: on-failure
    ports:
      - 8089:8089
    depends_on:
      - mysqldb

