version: "3.3"
services:
  mysqldb:
    container_name: mysqldb
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: balkis00
      MYSQL_DATABASE: kaddem

    volumes:
      - /home/mysql/data:/var/lib/mysql

  spring_app:
    image: balkismelki/kaddem2
    container_name: kaddemproject
    restart: on-failure
    ports:
      - "9091:9091"
    depends_on:
      - mysqldb