version: '1'
services:
  backend:
    image: asmahejaiej/jenkins-releases:v1.0.0

    ports:
      - "8089:8089"
    links:
      - mysqldb
  mysqldb:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: kaddem
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root